import uuid

from tortoise import fields, Model


class Nutrition(Model):
    id = fields.UUIDField(pk=True, default=uuid.uuid4)
    NDB_No = fields.IntField()
    Shrt_Desc = fields.CharField(max_length=255)
    Water_g = fields.FloatField()
    Energ_Kcal = fields.IntField()
    Protein_g = fields.FloatField()
    Lipid_Tot_g = fields.FloatField()
    Ash_g = fields.FloatField()
    Carbohydrt_g = fields.FloatField()
    Fiber_TD_g = fields.FloatField()
    Sugar_Tot_g = fields.FloatField()
    Calcium_mg = fields.FloatField()
    Iron_mg = fields.FloatField()
    Magnesium_mg = fields.FloatField()
    Phosphorus_mg = fields.FloatField()
    Potassium_mg = fields.FloatField()
    Sodium_mg = fields.FloatField()
    Zinc_mg = fields.FloatField()
    Copper_mg = fields.FloatField()
    Manganese_mg = fields.FloatField()
    Selenium_µg = fields.FloatField()
    Vit_C_mg = fields.FloatField()
    Thiamin_mg = fields.FloatField()
    Riboflavin_mg = fields.FloatField()
    Niacin_mg = fields.FloatField()
    Panto_Acid_mg = fields.FloatField()
    Vit_B6_mg = fields.FloatField()
    Folate_Tot_µg = fields.FloatField()
    Folic_Acid_µg = fields.FloatField()
    Food_Folate_µg = fields.FloatField()
    Folate_DFE_µg = fields.FloatField()
    Choline_Tot_mg = fields.FloatField()
    Vit_B12_µg = fields.FloatField()
    Vit_A_IU = fields.FloatField()
    Vit_A_RAE = fields.FloatField()
    Retinol_µg = fields.FloatField()
    Alpha_Carot_µg = fields.FloatField()
    Beta_Carot_µg = fields.FloatField()
    Beta_Crypt_µg = fields.FloatField()
    Lycopene_µg = fields.FloatField()
    Lut_Zea_µg = fields.FloatField()
    Vit_E_mg = fields.FloatField()
    Vit_D_µg = fields.FloatField()
    Vit_D_IU = fields.FloatField()
    Vit_K_µg = fields.FloatField()
    FA_Sat_g = fields.FloatField()
    FA_Mono_g = fields.FloatField()
    FA_Poly_g = fields.FloatField()
    Cholestrl_mg = fields.FloatField()
    GmWt_1 = fields.FloatField()
    GmWt_Desc1 = fields.CharField(max_length=255)
    GmWt_2 = fields.FloatField()
    GmWt_Desc2 = fields.CharField(max_length=255)
    Refuse_Pct = fields.FloatField()
